import os
from dotenv import load_dotenv
from algorithm import generate_password, generate_password2

load_dotenv()

def run():
  print("Program is running 🏃")

  long = int(input("Type how many characters you want your password: ?"))
  if( os.environ.get("MODE") == "MYPROGRAM"):
    print("This password was generated by my program: 🐲")
    password = generate_password(long)
  else:
    print("This password was generated by a module: 🤣")
    password = generate_password2(long)

  print(password)

if __name__ == "__main__":
  run()